'use client';
export { Canvas2, Canvas2Editor, default } from './editor/Canvas2';
export type { Canvas2EditorProps, Canvas2Api, Canvas2Scene } from './editor/Canvas2';
export type { CanvasWorkspace } from './workspaces/types';
export { CanvasMenu } from './navigation/CanvasMenu';
export type { CanvasMenuProps } from './navigation/CanvasMenu';
export { PageNavigator } from './navigation/PageNavigator';
export type { PageNavigatorProps } from './navigation/PageNavigator';
export { LayersPanel } from './panels/LayersPanel';
export type { LayersPanelProps } from './panels/LayersPanel';
export { DesignPanel } from './panels/DesignPanel';
export type { DesignPanelProps } from './panels/DesignPanel';
export { BrandGallery } from './panels/BrandGallery';
export type { BrandGalleryProps } from './panels/BrandGallery';
export { LibraryPanel } from './panels/LibraryPanel';
export type { LibraryPanelProps } from './panels/LibraryPanel';
export { PageActions } from './navigation/PageActions';
export type { PageActionsProps } from './navigation/PageActions';
export { VideoFramePicker } from './overlays/VideoFramePicker';
export type { VideoFramePickerProps } from './overlays/VideoFramePicker';
export { DragPreview } from './overlays/DragPreview';
export type { DragPreviewProps } from './overlays/DragPreview';
export { DEFAULT_LABELS, mergeLabels } from './shared/labels';
export type { Canvas2Labels, PartialLabels } from './shared/labels';
export { palette, PANEL_FONT } from './shared/theme';
